### PR TITLE
Changes for version MySensors 2.3.x

### PR DESCRIPTION
**Pull request by Haba1234**

### CODE REVIEW

**Comment by GermanBluefox** [comment]
Are there any plans about merging it? 
We want to use it in our project and cannot link it.
It would be nice if new version will appear on npm.

**Comment by GermanBluefox** [comment]
Ping?

**Comment by Apollon77** [comment]
@geek maybe allow additional maintainers to keep this mobule alive? I do not think that a fork is needed ;-)

**Review by geek — APPROVED** [review]

**Comment by geek** [comment]
@GermanBluefox thanks for the ping... I never received the email notification from a while back. Publishing as 2.0.0 as this appears to be a break from the old version

**Comment by GermanBluefox** [comment]
@geek Thank you :)

**Pull request merged**
